<a href="https://colab.research.google.com/github/swKyungbock/2023MLwithTextData/blob/main/6%EC%9E%A5_%5B%EC%B0%B8%EA%B3%A0%5DLightGBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 레드 와인과 화이트 와인의 분류


## 여러가지 방법으로 분류해 보기

1.   RandomForest
2.   GradientBoosting
3. LGBM



In [1]:
#필요한 라이브러리 임포트
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#데이터 가져오기
wine=pd.read_csv('https://bit.ly/wine_csv_data')

data=wine[['alcohol','sugar','pH']].to_numpy()
target=wine['class'].to_numpy()

#트레이닝용 데이터와 테스트용 데이터 분리하기
train_input, test_input, train_target, test_target=train_test_split(data, target,test_size=0.2, random_state=42)


### 랜덤 포레스트로 훈련하기

In [3]:
#랜덤 포레스트로 훈련하기
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.feature_importances_)
print(rf.score(train_input, train_target))
print(rf.score(test_input, test_target))

[0.23167441 0.50039841 0.26792718]
0.996921300750433
0.8892307692307693


## 랜덤 포레스트의 oob(Out Of Box) 이용하기

In [4]:
#랜덤 포레스트의 oob(Out Of Box) 이용하기
rf=RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.feature_importances_)
print(rf.oob_score_)
print(rf.score(train_input, train_target))
print(rf.score(test_input, test_target))

[0.23167441 0.50039841 0.26792718]
0.8934000384837406
0.996921300750433
0.8892307692307693


##그레이디언트 부스팅

In [5]:
#그레이디언트 부스팅
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
gb.fit(train_input,train_target)
print(gb.feature_importances_)
print(gb.score(train_input, train_target))
print(gb.score(test_input, test_target))


[0.15872278 0.68010884 0.16116839]
0.9382335963055609
0.8707692307692307


##히스토그램기반 그레이디언트 부스팅

In [9]:
#히스토그램기반 그레이디언트 부스팅
from sklearn.ensemble import HistGradientBoostingClassifier
hgb=HistGradientBoostingClassifier(random_state=42)
hgb.fit(train_input,train_target)

print(hgb.score(train_input, train_target))
print(hgb.score(test_input, test_target))


0.924956705791803
0.8723076923076923


##LightGBM

In [10]:
#LightGBM
from lightgbm import LGBMClassifier
lgb=LGBMClassifier(random_state=42)
lgb.fit(train_input,train_target)

print(lgb.score(train_input, train_target))
print(lgb.score(test_input, test_target))

[LightGBM] [Info] Number of positive: 3939, number of negative: 1258
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000217 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 380
[LightGBM] [Info] Number of data points in the train set: 5197, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.757937 -> initscore=1.141404
[LightGBM] [Info] Start training from score 1.141404
0.9288050798537618
0.8730769230769231
